dev_addr: 127.0.0.1:8000
site_name: Benjamin-Internal
nav:
  - Home: index.md
  - BaTool: batool.md
  - AccJoon: 
    - Description: accjoon.md
    - Script:
      - Script: accjoon/AccScript.md
      - Acc Commands: accjoon/AccCommands.md
      - Application Commands: accjoon/AppCommands.md
      - Name Pipe Commands: accjoon/NPCommands.md
      - Miscellaneous Commands: accjoon/MiscCommands.md
      - Programming Commands: accjoon/ProgCommands.md
      - Uia Commands: accjoon/UiaCommands.md
      - Examples: accjoon/Examples.md
  - Rebound: rebound.md
  - Mom: mom.md
  - Arbade: arbade.md
  - ENN: enn.md
  - GitHub: https://github.com/bijanbina/Benjamin
theme:
  name: windmill
  palette:
    primary: 'indigo'
    accent: 'pink'
  favicon: 'img/favicon.ico'